#!/bin/bash

python3 tools/palfix.py gfx/pokemon/chimchar/front.png
python3 tools/palfix.py gfx/pokemon/chimchar/back.png
python3 tools/palfix.py gfx/pokemon/monferno/front.png
python3 tools/palfix.py gfx/pokemon/monferno/back.png
python3 tools/palfix.py gfx/pokemon/infernape/front.png
python3 tools/palfix.py gfx/pokemon/infernape/back.png
python3 tools/palfix.py gfx/pokemon/piplup/front.png
python3 tools/palfix.py gfx/pokemon/piplup/back.png
python3 tools/palfix.py gfx/pokemon/prinplup/front.png
python3 tools/palfix.py gfx/pokemon/prinplup/back.png
python3 tools/palfix.py gfx/pokemon/empoleon/front.png
python3 tools/palfix.py gfx/pokemon/empoleon/back.png
python3 tools/palfix.py gfx/pokemon/turtwig/front.png
python3 tools/palfix.py gfx/pokemon/turtwig/back.png
python3 tools/palfix.py gfx/pokemon/grotle/front.png
python3 tools/palfix.py gfx/pokemon/grotle/back.png
python3 tools/palfix.py gfx/pokemon/torterra/front.png
python3 tools/palfix.py gfx/pokemon/torterra/back.png
python3 tools/palfix.py gfx/pokemon/starly/front.png
python3 tools/palfix.py gfx/pokemon/starly/back.png
python3 tools/palfix.py gfx/pokemon/staravia/front.png
python3 tools/palfix.py gfx/pokemon/staravia/back.png
python3 tools/palfix.py gfx/pokemon/staraptor/front.png
python3 tools/palfix.py gfx/pokemon/staraptor/back.png
python3 tools/palfix.py gfx/pokemon/bidoof/front.png
python3 tools/palfix.py gfx/pokemon/bidoof/back.png
python3 tools/palfix.py gfx/pokemon/bibarel/front.png
python3 tools/palfix.py gfx/pokemon/bibarel/back.png
python3 tools/palfix.py gfx/pokemon/kricketot/front.png
python3 tools/palfix.py gfx/pokemon/kricketot/back.png
python3 tools/palfix.py gfx/pokemon/kricketune/front.png
python3 tools/palfix.py gfx/pokemon/kricketune/back.png
